- name: Install HTTP Packages
  apt: name=apache2 update_cache=yes state=latest
 
- name: Start httpd service
  systemd: name=apache2 state=started enabled=yes
 
- name: Create Apache Document Root
  file:
    path: "/var/www/{{ http_host }}"
    state: directory
    owner: "www-data"
    group: "www-data"
    mode: '0755'
 
- name: Set up Apache VirtualHost
  template:
    src: "files/apache2.conf"
    dest: "/etc/apache2/{{ http_conf }}"
    owner: root
    group: root
    mode: u=rw,g=r,o=r
